#!/bin/sh

qod="${QOTD_CACHE:-${HOME}/.config/qod.json}";
apiKey="${QOTD_API_KEY}";
dockerImage="${QOTD_IMAGE:-docker.io/mpepping/ponysay}";

if [ "$1" = '--help' ] || [ "$1" = '-h' ]; then
    echo Show a quote of the day and embed it in a ponysay.
    echo Built with love for both tools.
    echo See https://github.com/jeroenboersma/qotd-ponysay for more information
    exit 1;
fi

if [ -n "`which ponysay`" ]; then
    # native installation
    doit=ponysay;
elif [ -n "`which podman`" ]; then
    # podman installation
    doit="podman run --rm -it ${dockerImage}";
elif [ -n "`which docker`" ]; then
    # docker installation
    doit="docker run --rm -it ${dockerImage}";
elif [ -n "`which cowsay`" ]; then
    # fallback on cowsay
    doit=cowsay;
else
    echo I need at least podman or docker to run ponysay.
    echo https://podman.io/
    echo https://www.docker.com/
    exit 2;
fi

if [ "$1" = '--force' ] || [ "$1" = '-f' ] || [ ! -r "${qod}" ] || [ $(find "${qod}" -mtime +1 | wc -l) -gt 0 ]; then
    mkdir `dirname ${qod}`;
 
    if [ -z "${apiKey}" ] && [ ! -r "${qod}" ]; then 
        echo Grab yourself a api key and feed it to me.
        echo https://theysaidso.com/user/subscriptions
        echo export QOTD_API_KEY=[YOUR_API_KEY]
        exit 2;
    else
        curl -H "X-TheySaidSo-Api-Secret: ${apiKey}" https://quotes.rest/qod.json > "${qod}";
    fi
fi

clear;
quote=$(cat "${qod}" | jq -r '.contents.quotes[0].quote');

${doit} "${quote}";

